services:
  - name: telegram-bot
    type: web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd Telegram_Bot && python bot/bot.py
    envVars:
      - key: TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
